/* Aircell CloudSurfer GPIO Pins */
#define CLOUDSURFER_P1

#ifdef CLOUDSURFER_P1
#define AIRCELL_5V_ENABLE				159
#define AIRCELL_33V_ENABLE				150
#define AIRCELL_18V_ENABLE				149
#define AIRCELL_23V_ENABLE				95
#define AIRCELL_SOFTWARE_RESET			31
#define AIRCELL_WIFI_ENABLE_DETECT		94
#define AIRCELL_LCD_RESET				111
#define AIRCELL_CRADLE_DETECT			105
#define AIRCELL_BLUE_ENABLE				127
#define AIRCELL_GREEN_ENABLE			156
#define AIRCELL_RED_ENABLE				128
#define AIRCELL_LED_ENABLE				186
#define AIRCELL_EARPIECE_ENABLE			100
#define AIRCELL_RINGER_ENABLE			129
#define AIRCELL_VOLUME_UP_DETECT		164
#define AIRCELL_VOLUME_DOWN_DETECT		163
#define AIRCELL_HANDSET_DETECT			106
#define AIRCELL_TOUCH_RESET				61
#define AIRCELL_BATTERY_CUT_ENABLE		159
#define AIRCELL_PROX_INTERRUPT			98
#define AIRCELL_ACCEL_INTERRUPT			167
#define AIRCELL_TOUCH_INTERRUPT			126
#define AIRCELL_LCD_POWER_ENABLE		155
#define AIRCELL_BACKLIGHT_ENABLE		8
#endif

#ifdef CLOUDSURFER_P2
#define AIRCELL_5VA_ENABLE				134
#define AIRCELL_5VD_ENABLE				150
#define AIRCELL_18V_ENABLE				149
#define AIRCELL_SOFTWARE_RESET			31
#define AIRCELL_WIFI_ENABLE_DETECT		94
#define AIRCELL_LCD_RESET				111
#define AIRCELL_CRADLE_DETECT			105
#define AIRCELL_BLUE_ENABLE				127
#define AIRCELL_GREEN_ENABLE			156
#define AIRCELL_RED_ENABLE				128
#define AIRCELL_LED_ENABLE				186
#define AIRCELL_EARPIECE_ENABLE			163
#define AIRCELL_RINGER_ENABLE			129
#define AIRCELL_VOLUME_UP_DETECT		107
#define AIRCELL_VOLUME_DOWN_DETECT		108
#define AIRCELL_HANDSET_DETECT			106
#define AIRCELL_TOUCH_RESET				61
#define AIRCELL_BATTERY_CUT_ENABLE		159
#define AIRCELL_PROX_INTERRUPT			98
#define AIRCELL_ACCEL_INTERRUPT			167
#define AIRCELL_TOUCH_INTERRUPT			126
#define AIRCELL_CAMERA_PWDN				95
#define AIRCELL_BACKLIGHT_ENABLE		164
#endif

